require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::DocsController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Doc. As you add validations to Admin::Doc, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all admin_docs as @admin_docs" do
      doc = Admin::Doc.create! valid_attributes
      get :index
      assigns(:admin_docs).should eq([doc])
    end
  end

  describe "GET show" do
    it "assigns the requested doc as @doc" do
      doc = Admin::Doc.create! valid_attributes
      get :show, :id => doc.id
      assigns(:doc).should eq(doc)
    end
  end

  describe "GET new" do
    it "assigns a new doc as @doc" do
      get :new
      assigns(:doc).should be_a_new(Admin::Doc)
    end
  end

  describe "GET edit" do
    it "assigns the requested doc as @doc" do
      doc = Admin::Doc.create! valid_attributes
      get :edit, :id => doc.id
      assigns(:doc).should eq(doc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Doc" do
        expect {
          post :create, :doc => valid_attributes
        }.to change(Admin::Doc, :count).by(1)
      end

      it "assigns a newly created doc as @doc" do
        post :create, :doc => valid_attributes
        assigns(:doc).should be_a(Admin::Doc)
        assigns(:doc).should be_persisted
      end

      it "redirects to the created doc" do
        post :create, :doc => valid_attributes
        response.should redirect_to(Admin::Doc.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved doc as @doc" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Doc.any_instance.stub(:save).and_return(false)
        post :create, :doc => {}
        assigns(:doc).should be_a_new(Admin::Doc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Doc.any_instance.stub(:save).and_return(false)
        post :create, :doc => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested doc" do
        doc = Admin::Doc.create! valid_attributes
        # Assuming there are no other admin_docs in the database, this
        # specifies that the Admin::Doc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Doc.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => doc.id, :doc => {'these' => 'params'}
      end

      it "assigns the requested doc as @doc" do
        doc = Admin::Doc.create! valid_attributes
        put :update, :id => doc.id, :doc => valid_attributes
        assigns(:doc).should eq(doc)
      end

      it "redirects to the doc" do
        doc = Admin::Doc.create! valid_attributes
        put :update, :id => doc.id, :doc => valid_attributes
        response.should redirect_to(doc)
      end
    end

    describe "with invalid params" do
      it "assigns the doc as @doc" do
        doc = Admin::Doc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Doc.any_instance.stub(:save).and_return(false)
        put :update, :id => doc.id, :doc => {}
        assigns(:doc).should eq(doc)
      end

      it "re-renders the 'edit' template" do
        doc = Admin::Doc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Doc.any_instance.stub(:save).and_return(false)
        put :update, :id => doc.id, :doc => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested doc" do
      doc = Admin::Doc.create! valid_attributes
      expect {
        delete :destroy, :id => doc.id
      }.to change(Admin::Doc, :count).by(-1)
    end

    it "redirects to the admin_docs list" do
      doc = Admin::Doc.create! valid_attributes
      delete :destroy, :id => doc.id
      response.should redirect_to(admin_docs_url)
    end
  end

end
