defaults: &defaults
  app_name: "API Docs"
  domain: "127.0.0.1:3000"
  google_analytics_key: "apikey"
  foot_html: "&copy; API Docs."

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults