defaults: &defaults
  app_name: "API Document"
  neat_setting: 24
  google_analytics_key: "apikey"

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults