defaults: &defaults
  app_name: "API Document"
  domain: "127.0.0.1:3000"
  google_analytics_key: "apikey"
  foot_html: "&copy; API Document."

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults