defaults: &defaults
  host: '127.0.0.1'
  autocreate_indexes: false
  allow_dynamic_fields: true
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true
  reconnect_time: 5

development:
  <<: *defaults
  database: wiki_development

test:
  <<: *defaults
  database: wiki_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: '127.0.0.1'
  database: wiki
  # port: <%#= ENV['MONGOID_PORT'] || '28017' %>
  # username: <%#= ENV['MONGOID_USERNAME'] %>
  # password: <%#= ENV['MONGOID_PASSWORD'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
